"""initial_tables

Revision ID: c488952aadf1
Revises: 
Create Date: 2026-10-06 13:17:43.564723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c488952aadf1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_id'), 'patients', ['id'], unique=False)
    op.create_index(op.f('ix_patients_patient_id'), 'patients', ['patient_id'], unique=True)
    op.create_table('source_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_fk', sa.Integer(), nullable=False),
    sa.Column('source_label', sa.String(length=128), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('normalised_lines', sa.JSON(), nullable=False),
    sa.Column('line_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_fk'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_notes_id'), 'source_notes', ['id'], unique=False)
    op.create_table('summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_fk', sa.Integer(), nullable=False),
    sa.Column('source_note_fk', sa.Integer(), nullable=True),
    sa.Column('summary_json', sa.JSON(), nullable=False),
    sa.Column('chief_complaint', sa.Text(), nullable=True),
    sa.Column('allergy_count', sa.Integer(), nullable=True),
    sa.Column('medication_count', sa.Integer(), nullable=True),
    sa.Column('unverified_field_count', sa.Integer(), nullable=True),
    sa.Column('has_unverified', sa.Boolean(), nullable=True),
    sa.Column('model_used', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_fk'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['source_note_fk'], ['source_notes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_summaries_id'), 'summaries', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_summaries_id'), table_name='summaries')
    op.drop_table('summaries')
    op.drop_index(op.f('ix_source_notes_id'), table_name='source_notes')
    op.drop_table('source_notes')
    op.drop_index(op.f('ix_patients_patient_id'), table_name='patients')
    op.drop_index(op.f('ix_patients_id'), table_name='patients')
    op.drop_table('patients')
    # ### end Alembic commands ###
